name: Build macOS App

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install .NET MAUI workload
        run: dotnet workload install maui

      - name: Restore dependencies
        run: dotnet restore "NextUI Setup Wizard.csproj"

      - name: Build and publish for macOS (ARM64)
        run: |
          dotnet publish "NextUI Setup Wizard.csproj" -f net9.0-maccatalyst -c Release \
            -p:RuntimeIdentifier=maccatalyst-arm64 \
            -p:CreatePackage=true \
            -p:CodesignKey="" \
            -p:CodesignEntitlements="" \
            -p:EnableCodeSigning=false \
            -p:PublishTrimmed=true \
            -o ./publish/macos-arm64

      - name: Upload macOS ARM64 build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NextUI-Setup-Wizard_arm64
          path: ./publish/macos-arm64/
          retention-days: 30
